# Generated by Django 2.2.6 on 2019-10-15 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='follow_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(related_name='custom_user_follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='register_tag',
            field=models.ManyToManyField(related_name='custom_user_register_tag', to='tags.Tag'),
        ),
    ]
