# Generated by Django 2.2.6 on 2019-10-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191015_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='icon',
            new_name='origin',
        ),
    ]
