# Generated by Django 2.2.6 on 2019-10-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191017_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='origin',
            new_name='icon',
        ),
    ]
