# Generated by Django 2.2.6 on 2019-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191021_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(default='/var/www/nerorei/static/images/momiji.png', upload_to='icon/', verbose_name='アイコン'),
        ),
    ]
