# Generated by Django 2.2.6 on 2019-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191021_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(default='momiji.png', upload_to='icon/', verbose_name='アイコン'),
        ),
    ]
