# Generated by Django 2.2.6 on 2019-10-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191022_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='register_tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='custom_user_register_tag', to='tags.Tag'),
        ),
    ]
