# Generated by Django 2.2.6 on 2019-10-21 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191022_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='custom_user_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
